spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jip
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: csgit47@gmail.com
    password: svvuwvdjrbiucehn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      access-key: AKIATG6MG2AF2CR3CFO7
      secret-key: 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
    region:
      static: ap-southeast-2
    stack:
      auto: false

application:
  bucket:
    name: jip.upload.files

  # Thêm cấu hình cho đường dẫn file HTML và CSV
  file-paths:
    html-path: "src/main/resources/static/all-class-student.html"

cloudinary:
  cloud-name: dmlethtuv
  api-key: 151443119214651
  api-secret: LRXCKQiCmQNqx-GP4RFnOdf_xwY

