@startuml
actor Teacher
activate Teacher
Teacher -> StudentAssignmentController : PUT student-assignmemt/grade-submitted-assignment\n(studentAssignmentId, StudentAssignmentGradeRequest)
activate StudentAssignmentController

StudentAssignmentController -> Service : gradeSubmittedAssignment(studentAssignmentId, StudentAssignmentGradeRequest)
activate Service

Service -> StudentAssignmentRepository : findById(studentAssignmentId)
activate StudentAssignmentRepository
StudentAssignmentRepository --> Service : StudentAssignment


alt StudentAssignment found

    Service -> Service : setMark(request.mark)

    Service -> Service : setStatus(request.status)
    Service -> StudentAssignmentRepository : save(StudentAssignment)

    StudentAssignmentRepository --> Service : Updated StudentAssignment

    deactivate StudentAssignmentRepository
    Service --> StudentAssignmentController : return StudentAssignment
    deactivate Service
    StudentAssignmentController --> Teacher : 200 OK\n"Grade submitted successfully."
else StudentAssignment not found
    Service --> StudentAssignmentController : NoSuchElementException
    deactivate Service
    StudentAssignmentController --> Teacher : 404 Not Found\n"studentAssignmentId not found!"
end

deactivate StudentAssignmentController
@enduml